config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "cocktails#index"
  resources :cocktails, only: %i[index show new create destroy] do
    resources :doses, only: %i[new create destroy]
  end
  resources :doses, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  has_one_attached :photo
  validates :name, uniqueness: true, presence: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :ingredient
  belongs_to :cocktail
  validates :description, presence: true
  validates :ingredient, presence: true, uniqueness: true
  validates :cocktail, uniqueness: { scope: :ingredient }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end
  def show
    @cocktail = Cocktail.find(params[:id])
  end
  def new
    @cocktail = Cocktail.new
  end
  def create
    @cocktail = Cocktail.new(cocktail_params)
    @ingredients = Ingredient.new
    if @cocktail.save
      redirect_to new_cocktail_dose_path(@cocktail)
    else
      render :new
    end
  end
  def destroy
    @cocktail = Cocktail.find(params[:id])
    @cocktail.destroy
    redirect_to cocktails_path
  end

  private
  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to new_cocktail_dose_path
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to @dose.cocktail
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/articles/index.html.erb
<!-- app/views/articles/index.html.erb -->
<%= cl_image_tag("THE_IMAGE_ID_FROM_LIBRARY",
      width: 400, height: 300, crop: :fill) %>

<!-- for face detection -->
<%= cl_image_tag("IMAGE_WITH_FACE_ID",
      width: 150, height: 150, crop: :thumb, gravity: :face) %>

app/views/cocktails/index.html.erb
<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1600276695810-f8c5e6e5496c?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=3904&q=80)">
  <div class="container">
  <h1 id="main-header">El Señor Cocktail</h1>
  </div>
</div>
<div class="container">
  <div class="btn">
    <%= link_to 'Create a cocktail', new_cocktail_path %>
  </div>
</div>
<div class="container-fluid m-12">
  <div class="container">All Cocktails (<%= @cocktails.length %>)</div>
  <div class="row">
    <% @cocktails.each do |cocktail| %>
            <!-- Dispaly default Picture or picture user has uploaded -->
        <% cocktail_photo = '' %>
        <% if cocktail.photo.attached? %>
          <% cocktail_photo = cl_image_path cocktail.photo.key, height: 300, width: 400, crop: :fill %>
        <% else %>
          <% cocktail_photo = asset_path 'cocktail.jpg' %>
        <% end %>
    <div class="col-md-4">
      <div class="card-bg-img" style="width: 100%; background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.8)), url(<%= cocktail_photo %>)">
        <div class="card-body">
          <h5 class="card-title"><%= cocktail.name.capitalize %></h5>
          <p class="card-text">This is a description of the yummy cocktail to make you super thirsty</p>
          <div class="card-footer">
            <%= link_to 'View Cocktail', cocktail_path(cocktail), class: 'card-link' %>
          </div>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>
</div>
</div>

app/views/cocktails/new.html.erb
<div class="container pt-3">
  <h1>Create a new cocktail</h1>
</div>
<div class="container">
<%= simple_form_for(@cocktail) do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :photo, as: :file %>
<div class="container">
  <%= f.submit "Add Cocktail", class:'btn' %>
</div>
<% end %>
</div>
</div>

app/views/cocktails/show.html.erb
<div class="container">
  <h1><%= @cocktail.name.capitalize %></h1>
</div>
  <div class="container-fluid">
   <img src="https://i2.wp.com/dishesdelish.com/wp-content/uploads/2018/08/Mojito-Cocktail-Recipe-Square-1.jpg" class="img-fluid" id="show-cocktail" alt="Responsive image">
   <div class="container">
    <% @cocktail.doses.each do |dose| %>
    <div class="row">
      <li class="list-inline-item"><%= dose.description %></li>
    <li class="list-inline-item"><%= dose.ingredient.name %></li>
    <li class="list-inline-item"><%= cl_image_tag @article.photo.key, height: 300, width: 400, crop: :fill %></li>
    </div>
    <% end %>
    <div class="container">
    <div class="list-inline">
    <li class="list-inline-item"><%= link_to 'Add Ingredient ', new_cocktail_dose_path(@cocktail) %></li>
    <li class="list-inline-item"><%= link_to 'Delete Cocktail ', cocktail_path(@cocktail), method: :delete, data: { confirm: "Are you sure, buddy?" } %></li>
    </div>
    </div>
  </div>
</div>

app/views/doses/new.html.erb
<div class="container">
  <h1>Add an ingredient</h1>
</div>
<div class="container">
  <%= simple_form_for [@cocktail, @dose] do |f| %>
  <%= f.input :description %>
  <%= f.association :ingredient %>
</div>
<div class="container">
  <%= f.submit "Add Dose", class:'btn btn-primary' %>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
<nav class="navbar navbar-expand-sm bg-light">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="/cocktails">
                  All Cocktails
                </a>
            </li>
        </ul>
    </nav>
  <body>
    <%= yield %>
  </body>
</html>